@startuml
[cassandra-autoconfigure-test] --up--> [spring-boot-autoconfigure]
[cassandra-autoconfigure-test] --up--> [spring-boot-configuration-processor]
[cassandra-autoconfigure-test] ...up...> [achilles-junit]
[cassandra-autoconfigure-test] ...up...> [cassandra-autoconfigure]
[cassandra-autoconfigure-test] ...up...> [cassandra-model-mutation]
[cassandra-autoconfigure-test] ...up...> [cassandra]
[cassandra-autoconfigure] --up--> [spring-boot-autoconfigure]
[cassandra-autoconfigure] --up--> [spring-boot-configuration-processor]
[cassandra-autoconfigure] --up--> [vault-authentication]
[cassandra-autoconfigure] ...up...> [cassandra-model-mutation]
[cassandra-autoconfigure] ...up...> [cassandra]
[cassandra-autoconfigure] ...up...> [spring-boot-actuator-autoconfigure]
[cassandra-batch] --up--> [cassandra-driver-core]
[cassandra-batch] --up--> [cassandra-driver-mapping]
[cassandra-external-test-database] --up--> [cassandra]
[cassandra-external-test-database] --up--> [spring-boot-configuration-processor]
[cassandra-external-test-database] --up--> [spring-context]
[cassandra-external-test-database] --up--> [spring-test]
[cassandra-model-mutation-common] --up--> [logging]
[cassandra-model-mutation-common] --up--> [spring-beans]
[cassandra-model-mutation] --up--> [cassandra-driver-core]
[cassandra-model-mutation] --up--> [cassandra-driver-mapping]
[cassandra-model-mutation] --up--> [cassandra-model-mutation-common]
[cassandra-model-mutation] --up--> [logging]
[cassandra-starter-test] --up--> [cassandra-autoconfigure-test]
[cassandra-starter-test] --up--> [cassandra-external-test-database]
[cassandra-starter-test] --up--> [cassandra-starter]
[cassandra-starter-test] --up--> [spring-boot-configuration-processor]
[cassandra-starter-test] --up--> [testsupport-cassandra]
[cassandra-starter] --up--> [cassandra-autoconfigure]
[cassandra-starter] --up--> [cassandra-batch]
[cassandra-starter] --up--> [cassandra-model-mutation]
[cassandra-starter] --up--> [cassandra]
[cassandra-starter] --up--> [spring-boot-configuration-processor]
[cassandra] --up--> [cassandra-driver-core]
[cassandra] --up--> [cassandra-driver-extras]
[cassandra] --up--> [cassandra-driver-mapping]
[cassandra] --up--> [logging]
[cassandra] --up--> [micrometer-core]
[cassandra] --up--> [opentracing-cassandra-driver-3]
[client-tokens-autoconfigure-test] --up--> [client-tokens-autoconfigure]
[client-tokens-autoconfigure-test] --up--> [spring-boot-autoconfigure]
[client-tokens-autoconfigure-test] --up--> [spring-boot-configuration-processor]
[client-tokens-autoconfigure-test] ...up...> [client-tokens-test]
[client-tokens-autoconfigure] --up--> [secrets-pipeline]
[client-tokens-autoconfigure] --up--> [spring-boot-autoconfigure]
[client-tokens-autoconfigure] --up--> [spring-boot-configuration-processor]
[client-tokens-autoconfigure] --up--> [vault-authentication]
[client-tokens-autoconfigure] ...up...> [client-tokens]
[client-tokens-autoconfigure] ...up...> [spring-webmvc]
[client-tokens-starter-test] --up--> [client-tokens-autoconfigure-test]
[client-tokens-starter-test] --up--> [client-tokens-test]
[client-tokens-starter-test] --up--> [spring-boot-configuration-processor]
[client-tokens-starter] --up--> [client-tokens-autoconfigure]
[client-tokens-starter] --up--> [client-tokens]
[client-tokens-starter] --up--> [spring-boot-configuration-processor]
[client-tokens-test] --up--> [client-tokens]
[client-tokens] --up--> [bcprov-jdk15on]
[client-tokens] --up--> [caffeine]
[client-tokens] --up--> [client-tokens-annotations]
[client-tokens] --up--> [error-handling]
[client-tokens] --up--> [jose4j]
[client-tokens] --up--> [logging]
[client-tokens] --up--> [spring-web]
[client-tokens] ...up...> [tomcat-embed-core]
[compliance] --up--> [slf4j-api]
[compliance] --up--> [spring-kafka]
[compliance] --up--> [validation-api]
[delete-user-autoconfigure] --up--> [spring-boot-autoconfigure]
[delete-user-autoconfigure] --up--> [spring-boot-configuration-processor]
[delete-user-autoconfigure] ...up...> [delete-user]
[delete-user-starter] --up--> [client-tokens-autoconfigure]
[delete-user-starter] --up--> [client-tokens]
[delete-user-starter] --up--> [delete-user-autoconfigure]
[delete-user-starter] --up--> [delete-user]
[delete-user-starter] --up--> [spring-boot-configuration-processor]
[delete-user] --up--> [client-tokens]
[delete-user] --up--> [error-handling]
[delete-user] --up--> [spring-boot-configuration-processor]
[delete-user] ...up...> [spring-web]
[delete-user] ...up...> [spring-webflux]
[error-handling] --up--> [jackson-databind]
[error-handling] --up--> [slf4j-api]
[error-handling] --up--> [swagger-annotations]
[error-handling] --up--> [swagger-annotations]
[error-handling] ...up...> [hibernate-validator]
[error-handling] ...up...> [spring-security-core]
[error-handling] ...up...> [spring-webmvc]
[error-handling] ...up...> [tomcat-embed-core]
[http] --up--> [slf4j-api]
[kafka-autoconfigure] --up--> [spring-boot-autoconfigure]
[kafka-autoconfigure] --up--> [spring-boot-configuration-processor]
[kafka-autoconfigure] --up--> [vault-authentication]
[kafka-autoconfigure] ...up...> [hibernate-validator]
[kafka-autoconfigure] ...up...> [jackson-core]
[kafka-autoconfigure] ...up...> [spring-boot-actuator-autoconfigure]
[kafka-autoconfigure] ...up...> [spring-kafka]
[kafka-external-test-cluster] --up--> [kafka]
[kafka-external-test-cluster] --up--> [spring-boot-autoconfigure]
[kafka-external-test-cluster] --up--> [spring-boot-configuration-processor]
[kafka-external-test-cluster] --up--> [spring-test]
[kafka-external-test-cluster] ...up...> [spring-kafka]
[local-team-starter] --up--> [commons-codec]
[local-team-starter] --up--> [commons-compress]
[local-team-starter] --up--> [okhttp]
[local-team-starter] --up--> [spring-boot-configuration-processor]
[local-team-starter] --up--> [yolt-service-spring-boot-starter]
[local-team-starter] ...up...> [cassandra-autoconfigure]
[local-team-starter] ...up...> [kubernetes-client]
[local-team-starter] ...up...> [spring-kafka]
[logging-test] --up--> [junit-jupiter-api]
[logging-test] --up--> [logback-classic]
[logging] --up--> [jackson-datatype-jsr310]
[logging] --up--> [jul-to-slf4j]
[logging] --up--> [log4j-to-slf4j]
[logging] --up--> [logback-classic]
[logging] --up--> [logstash-logback-encoder]
[lovebird-commons] ...up...> [lombok]
[monitoring] --up--> [micrometer-core]
[monitoring] --up--> [spring-aop]
[postgres-autoconfigure] --up--> [spring-boot-autoconfigure]
[postgres-autoconfigure] --up--> [spring-boot-configuration-processor]
[postgres-autoconfigure] --up--> [vault-authentication]
[postgres-autoconfigure] ...up...> [HikariCP]
[postgres-external-test-database] --up--> [postgresql]
[postgres-external-test-database] --up--> [spring-boot-configuration-processor]
[postgres-external-test-database] --up--> [spring-context]
[postgres-external-test-database] --up--> [spring-test]
[sample-app-cassandra-with-combined-spring-data-and-v3-client] --up--> [cassandra-starter]
[sample-app-cassandra-with-combined-spring-data-and-v3-client] --up--> [spring-data-cassandra-model-mutation]
[sample-app-cassandra-with-combined-spring-data-and-v3-client] --up--> [spring-data-cassandra]
[sample-app-cassandra-with-combined-spring-data-and-v3-client] --up--> [yolt-service-spring-boot-starter]
[sample-app-cassandra-with-spring-data] --up--> [spring-data-cassandra-model-mutation]
[sample-app-cassandra-with-spring-data] --up--> [spring-data-cassandra]
[sample-app-cassandra-with-spring-data] --up--> [yolt-service-spring-boot-starter]
[sample-app-cassandra-with-v3-client] --up--> [cassandra-starter]
[sample-app-cassandra-with-v3-client] --up--> [yolt-service-spring-boot-starter]
[sample-app-kafka-client-tokens] --up--> [client-tokens-starter]
[sample-app-kafka-client-tokens] --up--> [spring-kafka]
[sample-app-kafka-client-tokens] --up--> [yolt-service-spring-boot-starter]
[sample-app-kafka] --up--> [spring-kafka]
[sample-app-kafka] --up--> [yolt-service-spring-boot-starter]
[sample-app-postgres] --up--> [flyway-core]
[sample-app-postgres] --up--> [postgresql]
[sample-app-postgres] --up--> [spring-boot-starter-data-jpa]
[sample-app-postgres] --up--> [yolt-service-spring-boot-starter]
[sample-app-reactive] --up--> [spring-boot-starter-webflux]
[sample-app-reactive] --up--> [yolt-service-spring-boot-starter]
[sample-app-web-client-tokens] --up--> [client-tokens-starter]
[sample-app-web-client-tokens] --up--> [spring-boot-starter-web]
[sample-app-web-client-tokens] --up--> [yolt-service-spring-boot-starter]
[sample-app-web] --up--> [spring-boot-starter-web]
[sample-app-web] --up--> [yolt-service-spring-boot-starter]
[secrets-pipeline] --up--> [bcprov-jdk15on]
[secrets-pipeline] --up--> [jose4j]
[secrets-pipeline] --up--> [jpgpj]
[secrets-pipeline] --up--> [security-utils]
[secrets-pipeline] --up--> [spring-core]
[spring-data-cassandra-autoconfigure-test] --up--> [spring-boot-autoconfigure]
[spring-data-cassandra-autoconfigure-test] --up--> [spring-boot-configuration-processor]
[spring-data-cassandra-autoconfigure-test] --up--> [spring-data-cassandra-autoconfigure]
[spring-data-cassandra-autoconfigure-test] ...up...> [cassandra]
[spring-data-cassandra-autoconfigure-test] ...up...> [spring-data-cassandra-model-mutation]
[spring-data-cassandra-autoconfigure-test] ...up...> [spring-data-cassandra]
[spring-data-cassandra-autoconfigure] --up--> [spring-boot-autoconfigure]
[spring-data-cassandra-autoconfigure] --up--> [spring-boot-configuration-processor]
[spring-data-cassandra-autoconfigure] --up--> [vault-authentication]
[spring-data-cassandra-autoconfigure] ...up...> [spring-boot-actuator-autoconfigure]
[spring-data-cassandra-autoconfigure] ...up...> [spring-data-cassandra-model-mutation]
[spring-data-cassandra-autoconfigure] ...up...> [spring-data-cassandra]
[spring-data-cassandra-model-mutation] --up--> [cassandra-model-mutation-common]
[spring-data-cassandra-model-mutation] --up--> [logging]
[spring-data-cassandra-model-mutation] ...up...> [java-driver-core]
[spring-data-cassandra-model-mutation] ...up...> [java-driver-query-builder]
[springdoc-autoconfigure] --up--> [spring-boot-autoconfigure]
[springdoc-autoconfigure] --up--> [spring-boot-configuration-processor]
[springdoc-autoconfigure] ...up...> [springdoc]
[springdoc-starter] --up--> [spring-boot-configuration-processor]
[springdoc-starter] --up--> [springdoc-autoconfigure]
[springdoc-starter] --up--> [springdoc]
[springdoc] --up--> [spring-boot-autoconfigure]
[springdoc] --up--> [spring-boot-configuration-processor]
[springdoc] --up--> [springdoc-annotations]
[springdoc] --up--> [springdoc-openapi-ui]
[testsupport-cassandra] --up--> [assertj-core]
[testsupport-cassandra] --up--> [cassandra]
[testsupport-cassandra] --up--> [json-path]
[testsupport-cassandra] --up--> [junit-jupiter]
[testsupport-cassandra] --up--> [mockito-core]
[testsupport-cassandra] --up--> [spring-context]
[testsupport-cassandra] --up--> [spring-test]
[vault-authentication] --up--> [bcprov-jdk15on]
[vault-authentication] --up--> [logging]
[yolt-service-spring-boot-starter-test] --up--> [spring-boot-configuration-processor]
[yolt-service-spring-boot-starter-test] --up--> [spring-boot-starter-test]
[yolt-service-spring-boot-starter-test] --up--> [spring-boot-starter]
[yolt-service-spring-boot-starter-test] --up--> [spring-data-cassandra-autoconfigure-test]
[yolt-service-spring-boot-starter-test] --up--> [yolt-service-spring-boot-starter]
[yolt-service-spring-boot-starter-test] ...up...> [HikariCP]
[yolt-service-spring-boot-starter-test] ...up...> [spring-jdbc]
[yolt-service-spring-boot-starter-test] ...up...> [spring-kafka-test]
[yolt-service-spring-boot-starter] --up--> [error-handling]
[yolt-service-spring-boot-starter] --up--> [http]
[yolt-service-spring-boot-starter] --up--> [kafka-autoconfigure]
[yolt-service-spring-boot-starter] --up--> [logging]
[yolt-service-spring-boot-starter] --up--> [micrometer-registry-prometheus]
[yolt-service-spring-boot-starter] --up--> [monitoring]
[yolt-service-spring-boot-starter] --up--> [postgres-autoconfigure]
[yolt-service-spring-boot-starter] --up--> [secrets-pipeline]
[yolt-service-spring-boot-starter] --up--> [spring-boot-configuration-processor]
[yolt-service-spring-boot-starter] --up--> [spring-boot-starter-actuator]
[yolt-service-spring-boot-starter] --up--> [spring-boot-starter-aop]
[yolt-service-spring-boot-starter] --up--> [spring-boot-starter-logging]
[yolt-service-spring-boot-starter] --up--> [spring-boot-starter-validation]
[yolt-service-spring-boot-starter] --up--> [spring-boot-starter]
[yolt-service-spring-boot-starter] --up--> [spring-cloud-starter-bootstrap]
[yolt-service-spring-boot-starter] --up--> [spring-cloud-starter-config]
[yolt-service-spring-boot-starter] --up--> [spring-cloud-starter-sleuth]
[yolt-service-spring-boot-starter] --up--> [spring-data-cassandra-autoconfigure]
[yolt-service-spring-boot-starter] --up--> [vault-authentication]
[yolt-service-spring-boot-starter] ...up...> [auth]
[yolt-service-spring-boot-starter] ...up...> [spring-boot-starter-web]
[yolt-service-spring-boot-starter] ...up...> [spring-boot-starter-webflux]
@enduml
