@startuml
[cassandra-autoconfigure-test] ...up...> [cassandra-autoconfigure]
[cassandra-autoconfigure-test] ...up...> [cassandra-model-mutation]
[cassandra-autoconfigure-test] ...up...> [cassandra]
[cassandra-autoconfigure] --up--> [vault-authentication]
[cassandra-autoconfigure] ...up...> [cassandra-model-mutation]
[cassandra-autoconfigure] ...up...> [cassandra]
[cassandra-model-mutation-common] --up--> [logging]
[cassandra-model-mutation] --up--> [cassandra-model-mutation-common]
[cassandra-model-mutation] --up--> [logging]
[cassandra-starter-test] --up--> [cassandra-autoconfigure-test]
[cassandra-starter-test] --up--> [cassandra-external-test-database]
[cassandra-starter-test] --up--> [cassandra-starter]
[cassandra-starter-test] --up--> [testsupport-cassandra]
[cassandra-starter] --up--> [cassandra-autoconfigure]
[cassandra-starter] --up--> [cassandra-batch]
[cassandra-starter] --up--> [cassandra-model-mutation]
[cassandra-starter] --up--> [cassandra]
[cassandra] --up--> [logging]
[client-tokens-autoconfigure-test] --up--> [client-tokens-autoconfigure]
[client-tokens-autoconfigure-test] ...up...> [client-tokens-test]
[client-tokens-autoconfigure] --up--> [secrets-pipeline]
[client-tokens-autoconfigure] --up--> [vault-authentication]
[client-tokens-autoconfigure] ...up...> [client-tokens]
[client-tokens-starter-test] --up--> [client-tokens-autoconfigure-test]
[client-tokens-starter-test] --up--> [client-tokens-test]
[client-tokens-starter] --up--> [client-tokens-autoconfigure]
[client-tokens-starter] --up--> [client-tokens]
[client-tokens-test] --up--> [client-tokens]
[client-tokens] --up--> [client-tokens-annotations]
[client-tokens] --up--> [error-handling]
[client-tokens] --up--> [logging]
[delete-user-autoconfigure] ...up...> [delete-user]
[delete-user-starter] --up--> [client-tokens-autoconfigure]
[delete-user-starter] --up--> [client-tokens]
[delete-user-starter] --up--> [delete-user-autoconfigure]
[delete-user-starter] --up--> [delete-user]
[delete-user] --up--> [client-tokens]
[delete-user] --up--> [error-handling]
[kafka-autoconfigure] --up--> [vault-authentication]
[local-team-starter] --up--> [yolt-service-spring-boot-starter]
[local-team-starter] ...up...> [cassandra-autoconfigure]
[postgres-autoconfigure] --up--> [vault-authentication]
[sample-app-cassandra-with-combined-spring-data-and-v3-client] --up--> [cassandra-starter]
[sample-app-cassandra-with-combined-spring-data-and-v3-client] --up--> [spring-data-cassandra-model-mutation]
[sample-app-cassandra-with-combined-spring-data-and-v3-client] --up--> [yolt-service-spring-boot-starter]
[sample-app-cassandra-with-spring-data] --up--> [spring-data-cassandra-model-mutation]
[sample-app-cassandra-with-spring-data] --up--> [yolt-service-spring-boot-starter]
[sample-app-cassandra-with-v3-client] --up--> [cassandra-starter]
[sample-app-cassandra-with-v3-client] --up--> [yolt-service-spring-boot-starter]
[sample-app-kafka-client-tokens] --up--> [client-tokens-starter]
[sample-app-kafka-client-tokens] --up--> [yolt-service-spring-boot-starter]
[sample-app-kafka] --up--> [yolt-service-spring-boot-starter]
[sample-app-postgres] --up--> [yolt-service-spring-boot-starter]
[sample-app-reactive] --up--> [yolt-service-spring-boot-starter]
[sample-app-web-client-tokens] --up--> [client-tokens-starter]
[sample-app-web-client-tokens] --up--> [yolt-service-spring-boot-starter]
[sample-app-web] --up--> [yolt-service-spring-boot-starter]
[secrets-pipeline] --up--> [security-utils]
[spring-data-cassandra-autoconfigure-test] --up--> [spring-data-cassandra-autoconfigure]
[spring-data-cassandra-autoconfigure-test] ...up...> [spring-data-cassandra-model-mutation]
[spring-data-cassandra-autoconfigure] --up--> [vault-authentication]
[spring-data-cassandra-autoconfigure] ...up...> [spring-data-cassandra-model-mutation]
[spring-data-cassandra-model-mutation] --up--> [cassandra-model-mutation-common]
[spring-data-cassandra-model-mutation] --up--> [logging]
[springdoc-autoconfigure] ...up...> [springdoc]
[springdoc-starter] --up--> [springdoc-autoconfigure]
[springdoc-starter] --up--> [springdoc]
[springdoc] --up--> [springdoc-annotations]
[testsupport-cassandra] --up--> [cassandra]
[vault-authentication] --up--> [logging]
[yolt-service-spring-boot-starter-test] --up--> [spring-data-cassandra-autoconfigure-test]
[yolt-service-spring-boot-starter-test] --up--> [yolt-service-spring-boot-starter]
[yolt-service-spring-boot-starter] --up--> [error-handling]
[yolt-service-spring-boot-starter] --up--> [http]
[yolt-service-spring-boot-starter] --up--> [kafka-autoconfigure]
[yolt-service-spring-boot-starter] --up--> [logging]
[yolt-service-spring-boot-starter] --up--> [monitoring]
[yolt-service-spring-boot-starter] --up--> [postgres-autoconfigure]
[yolt-service-spring-boot-starter] --up--> [secrets-pipeline]
[yolt-service-spring-boot-starter] --up--> [spring-data-cassandra-autoconfigure]
[yolt-service-spring-boot-starter] --up--> [vault-authentication]
@enduml
