@startuml
[yolt-service-spring-boot-starter] --up--> [error-handling]
[yolt-service-spring-boot-starter] --up--> [http]
[yolt-service-spring-boot-starter] --up--> [kafka-autoconfigure]
[yolt-service-spring-boot-starter] --up--> [logging]
[yolt-service-spring-boot-starter] --up--> [micrometer-registry-prometheus]
[yolt-service-spring-boot-starter] --up--> [monitoring]
[yolt-service-spring-boot-starter] --up--> [postgres-autoconfigure]
[yolt-service-spring-boot-starter] --up--> [secrets-pipeline]
[yolt-service-spring-boot-starter] --up--> [spring-boot-configuration-processor]
[yolt-service-spring-boot-starter] --up--> [spring-boot-starter-actuator]
[yolt-service-spring-boot-starter] --up--> [spring-boot-starter-aop]
[yolt-service-spring-boot-starter] --up--> [spring-boot-starter-logging]
[yolt-service-spring-boot-starter] --up--> [spring-boot-starter-validation]
[yolt-service-spring-boot-starter] --up--> [spring-boot-starter]
[yolt-service-spring-boot-starter] --up--> [spring-cloud-starter-bootstrap]
[yolt-service-spring-boot-starter] --up--> [spring-cloud-starter-config]
[yolt-service-spring-boot-starter] --up--> [spring-cloud-starter-sleuth]
[yolt-service-spring-boot-starter] --up--> [spring-data-cassandra-autoconfigure]
[yolt-service-spring-boot-starter] --up--> [vault-authentication]
[yolt-service-spring-boot-starter] ...up...> [auth]
[yolt-service-spring-boot-starter] ...up...> [spring-boot-starter-web]
[yolt-service-spring-boot-starter] ...up...> [spring-boot-starter-webflux]
@enduml
